config/routes.rb
Foodmatrix::Application.routes.draw do
  
  resources :gls

  root 'welcome#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  get "/meals" => "meals#index"

  resources :ingredients

  resources :prep_ingredients

  resources :preps, except: [:create] do
    resources :prep_ingredients
  end

  resources :proteins do
    resources :preps, controller: "protein_preps", only: [:create]
  end

  resources :snacks do
    resources :preps, controller: "snack_preps", only: [:create]
  end

  resources :fats do
    resources :preps, controller: "fat_preps", only: [:create]
  end

  resources :spices do
    resources :preps, controller: "spice_preps", only: [:create]
  end

  resources :vegetables do
  	resources :preps, controller: "vegetable_preps", only: [:create]
  end

  resources :users do
    resources :gls
  end

  resources :grocery_lists

  resources :gls

  resources :gls do
    resources :grocery_lists
  end
  
end

app/models/fat.rb
class Fat < ActiveRecord::Base
	has_many :fat_preps, dependent: :destroy
	has_many :preps, through: :fat_preps
end

app/models/fat_prep.rb
class FatPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :fat
end

app/models/gl.rb
class Gl < ActiveRecord::Base
	belongs_to :user
	has_many :grocery_lists
end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
	has_many :gls
	has_many :users, through: :gls
	has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  	has_many :prep_ingredients
  	has_many :preps, through: :prep_ingredients
  	has_many :grocery_lists
end

app/models/meal.rb
class Meal
	attr_accessor :protein, :vegetable, :spice, :fat, :prep, :prep_protein, :prep_vegetable, :prep_spice 

	def initialize
		@protein = Protein.order("random()").first
		@vegetable = Vegetable.order("random()").first
		@spice = Spice.order("random()").first
		@prep_protein = @protein.preps.order("random()").first
		@prep_vegetable = @vegetable.preps.order("random()").first
		@prep_spice = @spice.preps.order("random()").first
	end
end

app/models/prep.rb
class Prep < ActiveRecord::Base
	has_many :protein_preps 
	has_many :proteins, through: :protein_preps
	has_many :vegetable_preps
	has_many :vegetables, through: :vegetable_preps
	has_many :fats, through: :fat_preps
	has_many :fat_preps
	has_many :spices, through: :spice_preps
	has_many :snack_preps
	has_many :snacks, through: :snack_preps
 	has_many :prep_ingredients, dependent: :destroy
  	has_many :ingredients, through: :prep_ingredients
end

app/models/protein.rb
#Validation here is optional - checks to make sure title is long enough
class Protein < ActiveRecord::Base
	has_many :protein_preps, dependent: :destroy
	has_many :preps, through: :protein_preps
	validates :title, presence: true
end

app/models/protein_prep.rb
class ProteinPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :protein
end

app/models/snack.rb
class Snack< ActiveRecord::Base
	has_many :snack_preps, dependent: :destroy
	has_many :preps, through: :snack_preps
end

app/models/snack_prep.rb
class SnackPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :snack
end

app/models/spice.rb
class Spice < ActiveRecord::Base
	has_many :spice_preps, dependent: :destroy
	has_many :preps, through: :spice_preps
end

app/models/spice_prep.rb
class SpicePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :spice
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
		format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
	has_one :gl
	has_many :grocery_lists, through: :gls
	

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
	      self.remember_token = User.encrypt(User.new_remember_token)
    	end
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
	has_many :vegetable_preps, dependent: :destroy
	has_many :preps, through: :vegetable_preps
end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  before_action :signed_in_user, only: [:create, :edit, :destroy]
  before_action :admin_user, only: [:create, :edit, :destroy]
  # GET /vegetables
  # GET /vegetables.json
  def index
    @vegetables = Vegetable.all
  end

  # GET /vegetables/1
  # GET /vegetables/1.json
  def show
    @vegetable = Vegetable.find(params[:id])
    @vegetables = @vegetable.preps.paginate(page: params[:page]) #makes the paginate function work
  end

  # GET /vegetables/new
  def new
    @vegetable = Vegetable.new
  end

  # GET /vegetables/1/edit
  def edit
    @vegetable = Vegetable.find(params[:id])
  end

  # POST /vegetables
  # POST /vegetables.json
  def create
    @vegetable = Vegetable.new(params[:vegetable].permit(:name, :body))

    if @vegetable.save
      redirect_to @vegetable
    else
      render 'new'
    end
  end

  # PATCH/PUT /vegetables/1
  # PATCH/PUT /vegetables/1.json
  def update
    @vegetable = Vegetable.find(params[:id])

    if @vegetable.update(params[:vegetable].permit(:name, :body))
      redirect_to @vegetable
    else
      render 'edit'
    end
  end

  # DELETE /vegetables/1
  # DELETE /vegetables/1.json
  def destroy
    @vegetable = Vegetable.find(params[:id])
    @vegetable.destroy

    redirect_to vegetables_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vegetable
      @vegetable = Vegetable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vegetable_params
      params.require(:vegetable).permit(:name, :body)
    end
end

app/helpers/fats_helper.rb
module FatsHelper
end

app/helpers/gls_helper.rb
module GlsHelper
end

app/helpers/preps_helper.rb
module PrepsHelper
end

app/helpers/spices_helper.rb
module SpicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/vegetables/_form.html.erb
<%= form_for @vegetable do |f| %>
  <% if @vegetable.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@fat.errors.count, "error") %> prohibited
      this vegetable from being saved:</h2>
    <ul>
    <% @vegetable.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/vegetables/_prepform.html.erb
	<div class="form_preparation">
<%= form_for([@vegetable, @vegetable.preps.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/vegetables/edit.html.erb
<h1>Editing Vegetable</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', vegetables_path %>

app/views/vegetables/index.html.erb
<h1>Listing Vegetables</h1>
 
<table class="food_index">
  <tr class="food_index_tr">
    <th >Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @vegetables.each do |vegetable| %>
  <tr>
    <td><%= link_to vegetable.name, vegetable_path(vegetable) %></td>
    <td class="text"><%= vegetable.body %></td>
    <td><%= link_to 'Show', vegetable_path(vegetable) %></td>
    <td><%= link_to 'Edit', edit_vegetable_path(vegetable) %></td>
    <td><%= link_to 'Delete', vegetable_path(vegetable), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Vegetable', new_vegetable_path %>
<%= link_to 'Home', root_path %>

app/views/vegetables/new.html.erb
<h1>New Vegetable</h1>

<%= render 'form' %>

<%= link_to 'Back', vegetables_path %>

app/views/vegetables/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @vegetable.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @vegetable.body %>
</p>

<div class="prep_or_recipe">
	<% if @vegetable.preps.any? %>
		<h2>Preparation Recipes: (<%= @vegetable.preps.count %>)</h2>
		<ol class="preps_list">
			<%= render @vegetable.preps %>
		</ol>
		<%= will_paginate @preps %>
	<% end %>
</div>

<div class="form">
	<h2>Add a Preparation Style:</h2>
<%= render "vegetables/prepform" %>
 </div>
<p></p>
<div class="food_bottom">
	<%= link_to 'Edit Vegetable', edit_vegetable_path(@vegetable) %> |
	<%= link_to 'Back to Vegetables', vegetables_path %>
</div>