config/routes.rb
Foodmatrix::Application.routes.draw do
  
  resources :gls

  root 'welcome#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  get "/meals" => "meals#index"

  resources :ingredients

  resources :prep_ingredients

  resources :preps, except: [:create] do
    resources :prep_ingredients
  end

  resources :proteins do
    resources :preps, controller: "protein_preps", only: [:create]
  end

  resources :snacks do
    resources :preps, controller: "snack_preps", only: [:create]
  end

  resources :fats do
    resources :preps, controller: "fat_preps", only: [:create]
  end

  resources :spices do
    resources :preps, controller: "spice_preps", only: [:create]
  end

  resources :vegetables do
  	resources :preps, controller: "vegetable_preps", only: [:create]
  end

  resources :users do
    resources :gls
  end

  resources :grocery_lists

  resources :gls

  resources :gls do
    resources :grocery_lists
  end
  
end

app/models/fat.rb
class Fat < ActiveRecord::Base
	has_many :fat_preps, dependent: :destroy
	has_many :preps, through: :fat_preps
end

app/models/fat_prep.rb
class FatPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :fat
end

app/models/gl.rb
class Gl < ActiveRecord::Base
	belongs_to :user
	has_many :grocery_lists
end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
	has_many :gls
	has_many :users, through: :gls
	has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  	has_many :prep_ingredients
  	has_many :preps, through: :prep_ingredients
  	has_many :grocery_lists
end

app/models/meal.rb
class Meal
	attr_accessor :protein, :vegetable, :spice, :fat, :prep, :prep_protein, :prep_vegetable, :prep_spice 

	def initialize
		@protein = Protein.order("random()").first
		@vegetable = Vegetable.order("random()").first
		@spice = Spice.order("random()").first
		@prep_protein = @protein.preps.order("random()").first
		@prep_vegetable = @vegetable.preps.order("random()").first
		@prep_spice = @spice.preps.order("random()").first
	end
end

app/models/prep.rb
class Prep < ActiveRecord::Base
	has_many :protein_preps 
	has_many :proteins, through: :protein_preps
	has_many :vegetable_preps
	has_many :vegetables, through: :vegetable_preps
	has_many :fats, through: :fat_preps
	has_many :fat_preps
	has_many :spices, through: :spice_preps
	has_many :snack_preps
	has_many :snacks, through: :snack_preps
 	has_many :prep_ingredients, dependent: :destroy
  	has_many :ingredients, through: :prep_ingredients
end

app/models/protein.rb
#Validation here is optional - checks to make sure title is long enough
class Protein < ActiveRecord::Base
	has_many :protein_preps, dependent: :destroy
	has_many :preps, through: :protein_preps
	validates :title, presence: true
end

app/models/protein_prep.rb
class ProteinPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :protein
end

app/models/snack.rb
class Snack< ActiveRecord::Base
	has_many :snack_preps, dependent: :destroy
	has_many :preps, through: :snack_preps
end

app/models/snack_prep.rb
class SnackPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :snack
end

app/models/spice.rb
class Spice < ActiveRecord::Base
	has_many :spice_preps, dependent: :destroy
	has_many :preps, through: :spice_preps
end

app/models/spice_prep.rb
class SpicePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :spice
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
		format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
	has_one :gl
	has_many :grocery_lists, through: :gls
	

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
	      self.remember_token = User.encrypt(User.new_remember_token)
    	end
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
	has_many :vegetable_preps, dependent: :destroy
	has_many :preps, through: :vegetable_preps
end

app/models/vegetable_prep.rb
class VegetablePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :vegetable
end

app/controllers/gls_controller.rb
class GlsController < ApplicationController
  before_action :set_gl, only: [:show, :edit, :update, :destroy]

  # GET /gls
  # GET /gls.json
  def index
    @gls = Gl.all
  end

  # GET /gls/1
  # GET /gls/1.json
  def show
  end

  # GET /gls/new
  def new
    @gl = Gl.new
  end

  # GET /gls/1/edit
  def edit
  end

  # POST /gls
  # POST /gls.json
  def create
    @gl = Gl.new(gl_params)

    respond_to do |format|
      if @gl.save
        format.html { redirect_to @gl, notice: 'Gl was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gl }
      else
        format.html { render action: 'new' }
        format.json { render json: @gl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gls/1
  # PATCH/PUT /gls/1.json
  def update
    respond_to do |format|
      if @gl.update(gl_params)
        format.html { redirect_to @gl, notice: 'Gl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gls/1
  # DELETE /gls/1.json
  def destroy
    @gl.destroy
    respond_to do |format|
      format.html { redirect_to gls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gl
      @gl = Gl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gl_params
      params.require(:gl).permit(:grocery_list_id, :user_id)
    end
end

app/helpers/fats_helper.rb
module FatsHelper
end

app/helpers/gls_helper.rb
module GlsHelper
end

app/helpers/preps_helper.rb
module PrepsHelper
end

app/helpers/spices_helper.rb
module SpicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gls/_form.html.erb
<%= form_for(@gl) do |f| %>
  <% if @gl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gl.errors.count, "error") %> prohibited this gl from being saved:</h2>

      <ul>
      <% @gl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grocery_list_id %><br>
    <%= f.number_field :grocery_list_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gls/edit.html.erb
<h1>Editing gl</h1>

<%= render 'form' %>

<%= link_to 'Show', @gl %> |
<%= link_to 'Back', gls_path %>

app/views/gls/index.html.erb
<h1>Listing gls</h1>

<table>
  <thead>
    <tr>
      <th>Grocery list</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gls.each do |gl| %>
      <tr>
        <td><%= gl.grocery_list_id %></td>
        <td><%= gl.user_id %></td>
        <td><%= link_to 'Show', gl %></td>
        <td><%= link_to 'Edit', edit_gl_path(gl) %></td>
        <td><%= link_to 'Destroy', gl, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gl', new_gl_path %>

app/views/gls/new.html.erb
<h1>New gl</h1>

<%= render 'form' %>

<%= link_to 'Back', gls_path %>

app/views/gls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grocery list:</strong>
  <%= @gl.grocery_list_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @gl.user_id %>
</p>

<%= link_to 'Edit', edit_gl_path(@gl) %> |
<%= link_to 'Back', gls_path %>