config/routes.rb
Foodmatrix::Application.routes.draw do
  
  resources :gls

  root 'welcome#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  get "/meals" => "meals#index"

  resources :ingredients

  resources :prep_ingredients

  resources :preps, except: [:create] do
    resources :prep_ingredients
  end

  resources :proteins do
    resources :preps, controller: "protein_preps", only: [:create]
  end

  resources :snacks do
    resources :preps, controller: "snack_preps", only: [:create]
  end

  resources :fats do
    resources :preps, controller: "fat_preps", only: [:create]
  end

  resources :spices do
    resources :preps, controller: "spice_preps", only: [:create]
  end

  resources :vegetables do
  	resources :preps, controller: "vegetable_preps", only: [:create]
  end

  resources :users do
    resources :gls
  end

  resources :grocery_lists

  resources :gls

  resources :gls do
    resources :grocery_lists
  end
  
end

app/models/fat.rb
class Fat < ActiveRecord::Base
	has_many :fat_preps, dependent: :destroy
	has_many :preps, through: :fat_preps
end

app/models/fat_prep.rb
class FatPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :fat
end

app/models/gl.rb
class Gl < ActiveRecord::Base
	belongs_to :user
	has_many :grocery_lists
end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
	has_many :gls
	has_many :users, through: :gls
	has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  	has_many :prep_ingredients
  	has_many :preps, through: :prep_ingredients
  	has_many :grocery_lists
end

app/models/meal.rb
class Meal
	attr_accessor :protein, :vegetable, :spice, :fat, :prep, :prep_protein, :prep_vegetable, :prep_spice 

	def initialize
		@protein = Protein.order("random()").first
		@vegetable = Vegetable.order("random()").first
		@spice = Spice.order("random()").first
		@prep_protein = @protein.preps.order("random()").first
		@prep_vegetable = @vegetable.preps.order("random()").first
		@prep_spice = @spice.preps.order("random()").first
	end
end

app/models/prep.rb
class Prep < ActiveRecord::Base
	has_many :protein_preps 
	has_many :proteins, through: :protein_preps
	has_many :vegetable_preps
	has_many :vegetables, through: :vegetable_preps
	has_many :fats, through: :fat_preps
	has_many :fat_preps
	has_many :spices, through: :spice_preps
	has_many :snack_preps
	has_many :snacks, through: :snack_preps
 	has_many :prep_ingredients, dependent: :destroy
  	has_many :ingredients, through: :prep_ingredients
end

app/models/protein.rb
#Validation here is optional - checks to make sure title is long enough
class Protein < ActiveRecord::Base
	has_many :protein_preps, dependent: :destroy
	has_many :preps, through: :protein_preps
	validates :title, presence: true
end

app/models/protein_prep.rb
class ProteinPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :protein
end

app/models/snack.rb
class Snack< ActiveRecord::Base
	has_many :snack_preps, dependent: :destroy
	has_many :preps, through: :snack_preps
end

app/models/snack_prep.rb
class SnackPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :snack
end

app/models/spice.rb
class Spice < ActiveRecord::Base
	has_many :spice_preps, dependent: :destroy
	has_many :preps, through: :spice_preps
end

app/models/spice_prep.rb
class SpicePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :spice
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
		format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
	has_one :gl
	has_many :grocery_lists, through: :gls
	

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
	      self.remember_token = User.encrypt(User.new_remember_token)
    	end
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
	has_many :vegetable_preps, dependent: :destroy
	has_many :preps, through: :vegetable_preps
end

app/models/vegetable_prep.rb
class VegetablePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :vegetable
end

app/controllers/fats_controller.rb
class FatsController < ApplicationController
 before_action :signed_in_user, only: [:create, :edit, :destroy]
  before_action :admin_user, only: [:create, :edit, :destroy]

  # GET /fats
  # GET /fats.json
  def index
    @fats = Fat.all
  end

  # GET /fats/1
  # GET /fats/1.json
  def show
    @fat = Fat.find(params[:id])
    @preps = @fat.preps.paginate(page: params[:page]) #makes the paginate function work
  end

  # GET /fats/new
  def new
    @fat = Fat.new
  end

  # GET /fats/1/edit
  def edit
    @fat = Fat.find(params[:id])
  end

  # POST /fats
  # POST /fats.json
  def create
    @fat = Fat.new(fat_params)

    respond_to do |format|
      if @fat.save
        format.html { redirect_to @fat, notice: 'Fat was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fat }
      else
        format.html { render action: 'new' }
        format.json { render json: @fat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fats/1
  # PATCH/PUT /fats/1.json
  def update
    respond_to do |format|
      if @fat.update(fat_params)
        format.html { redirect_to @fat, notice: 'Fat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fats/1
  # DELETE /fats/1.json
  def destroy
    @fat.destroy
    respond_to do |format|
      format.html { redirect_to fats_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fat
      @fat = Fat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fat_params
      params.require(:fat).permit(:name, :body)
    end
end

app/helpers/fats_helper.rb
module FatsHelper
end

app/helpers/gls_helper.rb
module GlsHelper
end

app/helpers/preps_helper.rb
module PrepsHelper
end

app/helpers/spices_helper.rb
module SpicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fats/_form.html.erb
<%= form_for @fat do |f| %>
  <% if @fat.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@fat.errors.count, "error") %> prohibited
      this fat from being saved:</h2>
    <ul>
    <% @fat.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/fats/_prepform.html.erb
	<div class="form_preparation">
<%= form_for([@fat, @fat.preps.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/fats/edit.html.erb
<h1>Editing Fat</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', proteins_path %>

app/views/fats/index.html.erb
<h1>Listing Fats</h1>
 
<table class="food_index">
  <tr class="food_index_tr">
    <th >Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @fats.each do |fat| %>
  <tr>
    <td><%= link_to fat.name, fat_path(fat) %></td>
    <td class="text"><%= fat.body %></td>
    <td><%= link_to 'Show', fat_path(fat) %></td>
    <td><%= link_to 'Edit', edit_fat_path(fat) %></td>
    <td><%= link_to 'Delete', fat_path(fat), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Fat', new_fat_path %>
<%= link_to 'Home', root_path %>

app/views/fats/new.html.erb
<h1>New Fat</h1>

<%= render 'form' %>

<%= link_to 'Back', fats_path %>

app/views/fats/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @fat.name %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @fat.body %>
</p>

<div class="prep_or_recipe">
	<% if @fat.preps.any? %>
		<h2>Preparation Recipes: (<%= @fat.preps.count %>)</h2>
		<ol class="preps_list">
			<%= render @fat.preps %>
		</ol>
		<%= will_paginate @preps %>
	<% end %>
</div>

<div class="form">
	<h2>Add a Preparation Style:</h2>
<%= render "fats/prepform" %>
 </div>
<p></p>
<div class="food_bottom">
	<%= link_to 'Edit Fat', edit_fat_path(@fat) %> |
	<%= link_to 'Back to Fats', fats_path %>
</div>