config/routes.rb
Foodmatrix::Application.routes.draw do
  
  resources :gls

  root 'welcome#index'
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
  get "/meals" => "meals#index"

  resources :ingredients

  resources :prep_ingredients

  resources :preps, except: [:create] do
    resources :prep_ingredients
  end

  resources :proteins do
    resources :preps, controller: "protein_preps", only: [:create]
  end

  resources :snacks do
    resources :preps, controller: "snack_preps", only: [:create]
  end

  resources :fats do
    resources :preps, controller: "fat_preps", only: [:create]
  end

  resources :spices do
    resources :preps, controller: "spice_preps", only: [:create]
  end

  resources :vegetables do
  	resources :preps, controller: "vegetable_preps", only: [:create]
  end

  resources :users do
    resources :gls
  end

  resources :grocery_lists

  resources :gls

  resources :gls do
    resources :grocery_lists
  end
  
end

app/models/fat.rb
class Fat < ActiveRecord::Base
	has_many :fat_preps, dependent: :destroy
	has_many :preps, through: :fat_preps
end

app/models/fat_prep.rb
class FatPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :fat
end

app/models/gl.rb
class Gl < ActiveRecord::Base
	belongs_to :user
	has_many :grocery_lists
end

app/models/grocery_list.rb
class GroceryList < ActiveRecord::Base
	has_many :gls
	has_many :users, through: :gls
	has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  	has_many :prep_ingredients
  	has_many :preps, through: :prep_ingredients
  	has_many :grocery_lists
end

app/models/meal.rb
class Meal
	attr_accessor :protein, :vegetable, :spice, :fat, :prep, :prep_protein, :prep_vegetable, :prep_spice 

	def initialize
		@protein = Protein.order("random()").first
		@vegetable = Vegetable.order("random()").first
		@spice = Spice.order("random()").first
		@prep_protein = @protein.preps.order("random()").first
		@prep_vegetable = @vegetable.preps.order("random()").first
		@prep_spice = @spice.preps.order("random()").first
	end
end

app/models/prep.rb
class Prep < ActiveRecord::Base
	has_many :protein_preps 
	has_many :proteins, through: :protein_preps
	has_many :vegetable_preps
	has_many :vegetables, through: :vegetable_preps
	has_many :fats, through: :fat_preps
	has_many :fat_preps
	has_many :spices, through: :spice_preps
	has_many :snack_preps
	has_many :snacks, through: :snack_preps
 	has_many :prep_ingredients, dependent: :destroy
  	has_many :ingredients, through: :prep_ingredients
end

app/models/protein.rb
#Validation here is optional - checks to make sure title is long enough
class Protein < ActiveRecord::Base
	has_many :protein_preps, dependent: :destroy
	has_many :preps, through: :protein_preps
	validates :title, presence: true
end

app/models/protein_prep.rb
class ProteinPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :protein
end

app/models/snack.rb
class Snack< ActiveRecord::Base
	has_many :snack_preps, dependent: :destroy
	has_many :preps, through: :snack_preps
end

app/models/snack_prep.rb
class SnackPrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :snack
end

app/models/spice.rb
class Spice < ActiveRecord::Base
	has_many :spice_preps, dependent: :destroy
	has_many :preps, through: :spice_preps
end

app/models/spice_prep.rb
class SpicePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :spice
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
		format: { with: VALID_EMAIL_REGEX }, 
		uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: { minimum: 6 }
	has_one :gl
	has_many :grocery_lists, through: :gls
	

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private
		def create_remember_token
	      self.remember_token = User.encrypt(User.new_remember_token)
    	end
end

app/models/vegetable.rb
class Vegetable < ActiveRecord::Base
	has_many :vegetable_preps, dependent: :destroy
	has_many :preps, through: :vegetable_preps
end

app/models/vegetable_prep.rb
class VegetablePrep < ActiveRecord::Base
	belongs_to :prep
	belongs_to :vegetable
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
	before_action :signed_in_user, only: [:create, :edit, :destroy]
	before_action :admin_user, only: [:create, :edit, :destroy]
	def index
		@snacks = Snack.all
	end

	def new
		@snack = Snack.new
	end

	def create
		@snack = Snack.new(params[:snack].permit(:name, :body))

		if @snack.save
			redirect_to @snack
		else
			render 'new'
		end
	end

	def edit
		@snack = find_snack
	end

	def update
		@snack = find_snack

		if @snack.update(params[:snack].permit(:name, :body))
			redirect_to @snack
		else
			render 'edit'
		end
	end

	def show
		@snack = find_snack
		@preps = @snack.preps.paginate(page: params[:page]) #makes the paginate function work
	end

	def update
		@snack = find_snack
		if @snack.update(params[:snack])
			redirect_to(@book)
		else
			render :edit
		end
	end

	def destroy
		@snack = Snack.find(params[:id])
		@snack.destroy

		redirect_to snacks_path
	end

private

	def find_snack
		Snack.find(params[:id])
	end
end

app/helpers/fats_helper.rb
module FatsHelper
end

app/helpers/gls_helper.rb
module GlsHelper
end

app/helpers/preps_helper.rb
module PrepsHelper
end

app/helpers/spices_helper.rb
module SpicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/snacks/_form.html.erb
<%= form_for @snack do |f| %>
  <% if @snack.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@snack.errors.count, "error") %> prohibited
      this snack from being saved:</h2>
    <ul>
    <% @snack.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/snacks/_prepform.html.erb
	<div class="form_preparation">
<%= form_for([@snack, @snack.preps.build]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :time %><br />
    <%= f.number_field :time %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
</div>

app/views/snacks/_snack.html.erb
<p>
  <strong>Name:</strong>
  <%= snack.name %>
</p>
 
<p>
  <strong>Details:</strong>
  <%= snack.body %>
</p>

app/views/snacks/edit.html.erb
<h1>Editing Snack</h1>

<%= render 'form' %>

<%= link_to 'Back', proteins_path %>

app/views/snacks/index.html.erb
<h1>Listing Snacks</h1>
 
<table class="food_index">
  <tr class="food_index_tr">
    <th >Title</th>
    <th>Text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @snacks.each do |snack| %>
  <tr>
    <td><%= link_to snack.name, snack_path(snack) %></td>
    <td class="text"><%= snack.name %></td>
    <td><%= link_to 'Show', snack_path(snack) %></td>
    <td><%= link_to 'Edit', edit_snack_path(snack) %></td>
    <td><%= link_to 'Delete', snack_path(snack), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Snack', new_snack_path %>
<%= link_to 'Home', root_path %>

app/views/snacks/new.html.erb
<h1>New Snack</h2>
<%= render 'form' %>

<%= link_to 'Back', snacks_path %>

app/views/snacks/show.html.erb

<%= render @snack %>

<div class="prep_or_recipe">
	<% if @snack.preps.any? %>
		<h2>Preparation Recipes: (<%= @snack.preps.count %>)</h2>
		<ol class="preps_list">
			<%= render @snack.preps %>
		</ol>
		<%= will_paginate @preps %>
	<% end %>
</div>

<div class="form">
	<h2>Add a Preparation Style:</h2>
	<%= render "snacks/prepform" %>
 </div>
<p></p>
<div class="food_bottom">
	<%= link_to 'Edit Snack', edit_snack_path(@snack) %> |
	<%= link_to 'Back to Snacks', snacks_path %>
</div>